name: docdoc
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  flutter_animate: ^4.2.0
  http: ^1.1.0
  auto_animated: ^3.2.0
  shared_preferences: ^2.2.1
  path: ^1.8.3
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  bloc: ^8.1.4
  dio: ^5.6.0
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  pretty_dio_logger: ^1.4.0
  easy_localization: ^3.0.7
  intl: ^0.19.0
  freezed: ^2.5.0
  flutter_svg: ^2.0.9
  get: ^4.6.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/

  # To add custom fonts to your application, add a fonts section here,
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

